packages:
  - esbuild-app
  - jest-tests
  - next-app
  - node-cjs-app
  - node-esm-app
  - parcel-app
  - rolldown-app
  - rsbuild-app
  - vite-app
  - vite-swc-app
  - webpack-4-app
  - webpack-5-app
  - scripts

catalog:
  '@base-ui/react': 1.1.0
