packages:
  - e2e-tests
  - scripts
  - src/*

allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  core-js: false
  esbuild: false
  fsevents: false
  lmdb: false
  msgpackr-extract: false
  sharp: false
  unrs-resolver: false

catalog:
  '@base-ui/react': 'https://pkg.pr.new/mui/base-ui/@base-ui/react@849178e'

blockExoticSubdeps: false
