packages:
  - astro-app
  - bun-app
  - esbuild-app
  - jest-tests
  - next-app
  - next-webpack-app
  - node-cjs-app
  - node-esm-app
  - parcel-app
  - react-router-app
  - rollup-app
  - rolldown-app
  - rsbuild-app
  - rspack-app
  - vite-app
  - vite-swc-app
  - vite-ssr-app
  - webpack-4-app
  - webpack-5-app
  - scripts

allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  core-js: false
  esbuild: false
  fsevents: false
  lmdb: false
  msgpackr-extract: false
  sharp: false
  unrs-resolver: false

catalog:
  '@base-ui/react': 'https://pkg.pr.new/mui/base-ui/@base-ui/react@849178e'

blockExoticSubdeps: false
