packages:
  - esbuild-app
  - jest-tests
  - next-app
  - node-cjs-app
  - node-esm-app
  - parcel-app
  - rolldown-app
  - rsbuild-app
  - vite-app
  - vite-swc-app
  - webpack-4-app
  - webpack-5-app
  - scripts

allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  core-js: false
  esbuild: false
  fsevents: false
  lmdb: false
  msgpackr-extract: false
  sharp: false
  unrs-resolver: false

catalog:
  '@base-ui/react': 1.5.0
